# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09698376a8b2ee7070118c34dc05ef124412f46b4e4abc7a0d1f23de5e76429b6361c78ff28b7b37e04a768e657de727fbfeaa354592609684785bd620603d06

test:
  secret_key_base: a1e0e33835240d020b36be336989eef7152b55238ce5236da898ea7d479850d77477cc64a06691b944b8ff72d232c7a42ad4f7b40581e20021b800d70bbb6f32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
